using Microsoft.EntityFrameworkCore;
using FloodGuardAdmin.Data;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("OracleConnection");

builder.Services.AddDbContext<AppDbContext>(
    options =>
    options.UseOracle(connectionString,
    compatibility => compatibility.UseOracleSQLCompatibility(OracleSQLCompatibility.DatabaseVersion19)));

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "FloodGuard Admin - Gestão de Ocorrências de Enchente",
        Version = "v1",
        Description = "API REST para gerenciamento de ocorrências, equipes de resposta e ações emergenciais do módulo administrativo FloodGuard."
    });

    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = System.IO.Path.Combine(AppContext.BaseDirectory, xmlFile);
    options.IncludeXmlComments(xmlPath);
});

var app = builder.Build();

// Criando as tabelas manualmente via SQL caso não existam
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var conn = db.Database.GetDbConnection();
    await conn.OpenAsync();

    var comandos = new[]
    {
        // Tabela de Ocorrências
        @"DECLARE v_count NUMBER;
          BEGIN
            SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'TBL_OCORRENCIAS_2TDSPI';
            IF v_count = 0 THEN
              EXECUTE IMMEDIATE 'CREATE TABLE TBL_OCORRENCIAS_2TDSPI (
                ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TITULO NVARCHAR2(200) NOT NULL,
                LOCALIZACAO NVARCHAR2(300) NOT NULL,
                NIVEL_SEVERIDADE NUMBER(10) NOT NULL,
                STATUS NVARCHAR2(50) NOT NULL,
                DATA_OCORRENCIA TIMESTAMP NOT NULL
              )';
            END IF;
          END;",

        // Tabela de Equipes de Resposta
        @"DECLARE v_count NUMBER;
          BEGIN
            SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'TBL_EQUIPES_RESPOSTA_2TDSPI';
            IF v_count = 0 THEN
              EXECUTE IMMEDIATE 'CREATE TABLE TBL_EQUIPES_RESPOSTA_2TDSPI (
                ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME NVARCHAR2(150) NOT NULL,
                ESPECIALIDADE NVARCHAR2(100) NOT NULL,
                CAPACIDADE_MAX NUMBER(10) NOT NULL,
                DISPONIVEL NUMBER(1) NOT NULL
              )';
            END IF;
          END;",

        // Tabela de Ações Emergenciais
        @"DECLARE v_count NUMBER;
          BEGIN
            SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'TBL_ACOES_EMERGENCIAIS_2TDSPI';
            IF v_count = 0 THEN
              EXECUTE IMMEDIATE 'CREATE TABLE TBL_ACOES_EMERGENCIAIS_2TDSPI (
                ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                DESCRICAO NVARCHAR2(500) NOT NULL,
                TIPO_ACAO NVARCHAR2(100) NOT NULL,
                DATA_INICIO TIMESTAMP NOT NULL,
                DATA_FIM TIMESTAMP NULL,
                STATUS_ACAO NVARCHAR2(50) NOT NULL,
                OCORRENCIA_ID NUMBER(10) NOT NULL,
                EQUIPE_RESPOSTA_ID NUMBER(10) NOT NULL,
                CONSTRAINT FK_ACOES_OCORRENCIA FOREIGN KEY (OCORRENCIA_ID) REFERENCES TBL_OCORRENCIAS_2TDSPI(ID) ON DELETE CASCADE,
                CONSTRAINT FK_ACOES_EQUIPE FOREIGN KEY (EQUIPE_RESPOSTA_ID) REFERENCES TBL_EQUIPES_RESPOSTA_2TDSPI(ID)
              )';
            END IF;
          END;"
    };

    foreach (var sql in comandos)
    {
        using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        await cmd.ExecuteNonQueryAsync();
    }

    await conn.CloseAsync();
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "FloodGuard Admin v1");
        options.RoutePrefix = "swagger";
    });
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();
