// <auto-generated />
using System;
using FloodGuardAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FloodGuardAdmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloodGuardAdmin.Models.Ocorrencia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");
                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("NVARCHAR2(200)")
                    .HasColumnName("TITULO");

                b.Property<string>("Localizacao")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("NVARCHAR2(300)")
                    .HasColumnName("LOCALIZACAO");

                b.Property<int>("NivelSeveridade")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("NIVEL_SEVERIDADE");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("STATUS");

                b.Property<DateTime>("DataOcorrencia")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("DATA_OCORRENCIA");

                b.HasKey("Id");
                b.ToTable("TBL_OCORRENCIAS_2TDSPI");
            });

            modelBuilder.Entity("FloodGuardAdmin.Models.EquipeResposta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");
                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("NVARCHAR2(150)")
                    .HasColumnName("NOME");

                b.Property<string>("Especialidade")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("ESPECIALIDADE");

                b.Property<int>("CapacidadeMax")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("CAPACIDADE_MAX");

                b.Property<bool>("Disponivel")
                    .HasColumnType("NUMBER(1)")
                    .HasColumnName("DISPONIVEL");

                b.HasKey("Id");
                b.ToTable("TBL_EQUIPES_RESPOSTA_2TDSPI");
            });

            modelBuilder.Entity("FloodGuardAdmin.Models.AcaoEmergencial", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("ID");
                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("DESCRICAO");

                b.Property<string>("TipoAcao")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("TIPO_ACAO");

                b.Property<DateTime>("DataInicio")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("DATA_INICIO");

                b.Property<DateTime?>("DataFim")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("DATA_FIM");

                b.Property<string>("StatusAcao")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)")
                    .HasColumnName("STATUS_ACAO");

                b.Property<int>("OcorrenciaId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("OCORRENCIA_ID");

                b.Property<int>("EquipeRespostaId")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("EQUIPE_RESPOSTA_ID");

                b.HasKey("Id");
                b.ToTable("TBL_ACOES_EMERGENCIAIS_2TDSPI");
            });
#pragma warning restore 612, 618
        }
    }
}
